odimra:
  namespace: odim 
  groupID:
  haDeploymentEnabled:
aciplugin:
  eventListenerNodePort: 30086
  aciPluginRootServiceUUID: 
  username: admin 
  password: sTfTyTZFvNj5zU5Tt0TfyDYU-ye3_ZqTMnMIj-LAeXaa8vCnBqq8Ga7zV6ZdfqQCdSAzmaO5AJxccD99UHLVlQ==
  lbHost: 
  lbPort: 30086
  logPath: /var/log/aciplugin_logs
  apicHost:
  apicUserName:
  apicPassword:
  apicDomainData:
